import os
import json

CACHE_DIR = os.path.expanduser("~/.config/compatflow")
CACHE_FILE = os.path.join(CACHE_DIR, "ports.json")

NATIVE = {
    "firefox": ("Firefox", "firefox", "Navegador"),
    "chrome": ("Chrome", "google-chrome-stable", "Navegador"),
    "edge": ("Edge", "microsoft-edge-stable", "Navegador"),
    "opera": ("Opera", "opera", "Navegador"),
    "brave": ("Brave", "brave-browser", "Navegador"),
    "vivaldi": ("Vivaldi", "vivaldi", "Navegador"),
    "chromium": ("Chromium", "chromium", "Navegador"),
    "maxthon": ("Maxthon", "maxthon", "Navegador"),
    "palemoon": ("Pale Moon", "palemoon", "Navegador"),
    "falkon": ("Falkon", "falkon", "Navegador"),
    "epiphany": ("Epiphany", "epiphany", "Navegador GNOME"),
    "konqueror": ("Konqueror", "konqueror", "Navegador KDE"),
    "discord": ("Discord", "discord", "Chat para gamers"),
    "telegram": ("Telegram", "telegram-desktop", "Mensagens"),
    "skype": ("Skype", "skypeforlinux", "Videochamadas"),
    "zoom": ("Zoom", "zoom", "Videochamadas"),
    "slack": ("Slack", "slack-desktop", "Trabalho"),
    "teams": ("Microsoft Teams", "teams", "Trabalho"),
    "signal": ("Signal", "signal-desktop", "Mensagens seguras"),
    "whatsapp": ("WhatsApp", "whatsapp-for-linux", "Mensagens"),
    "thunderbird": ("Thunderbird", "thunderbird", "Email"),
    "evolution": ("Evolution", "evolution", "Email/Calendario"),
    "geary": ("Geary", "geary", "Email GNOME"),
    "mumble": ("Mumble", "mumble", "Voz para jogos"),
    "vesktop": ("Vesktop", "vesktop", "Discord customizado"),
    "spotify": ("Spotify", "spotify", "Streaming de musica"),
    "vlc": ("VLC", "vlc", "Reprodutor de midia"),
    "mpv": ("MPV", "mpv", "Reprodutor de midia"),
    "celluloid": ("Celluloid", "celluloid", "Reprodutor GNOME"),
    "smplayer": ("SMPlayer", "smplayer", "Reprodutor"),
    "kodi": ("Kodi", "kodi", "Media Center"),
    "plex": ("Plex", "plex-media-server", "Media Server"),
    "jellyfin": ("Jellyfin", "jellyfin", "Media Server"),
    "emby": ("Emby", "emby-server", "Media Server"),
    "strawberry": ("Strawberry", "strawberry", "Player musica"),
    "rhythmbox": ("Rhythmbox", "rhythmbox", "Player musica"),
    "audacious": ("Audacious", "audacious", "Player musica"),
    "clementine": ("Clementine", "clementine", "Player musica"),
    "deadbeef": ("DeaDBeeF", "deadbeef", "Player musica"),
    "steam": ("Steam", "steam", "Plataforma de jogos"),
    "epic": ("Epic Games", "heroic-games-launcher-bin", "Epic Games"),
    "gog": ("GOG Galaxy", "heroic-games-launcher-bin", "GOG"),
    "lutris": ("Lutris", "lutris", "Gerenciador de jogos"),
    "minecraft": ("Minecraft", "minecraft-launcher", "Jogo"),
    "minetest": ("Minetest", "minetest", "Jogo open source"),
    "superTuxKart": ("SuperTuxKart", "supertuxkart", "Jogo"),
    "xonotic": ("Xonotic", "xonotic", "Jogo FPS"),
    "warzone2100": ("Warzone 2100", "warzone2100", "Jogo RTS"),
    "openTTD": ("OpenTTD", "openttd", "Jogo simulacao"),
    "openttd": ("OpenTTD", "openttd", "Jogo simulacao"),
    "flightgear": ("FlightGear", "flightgear", "Simulador de voo"),
    "neverball": ("Neverball", "neverball", "Jogo"),
    "libreoffice": ("LibreOffice", "libreoffice", "Escritorio completo"),
    "onlyoffice": ("OnlyOffice", "onlyoffice-desktopeditors", "Escritorio"),
    "wps": ("WPS Office", "wps-office", "Escritorio"),
    "softmaker": ("SoftMaker Office", "softmaker-freeoffice", "Escritorio"),
    "calligra": ("Calligra Suite", "calligra", "Escritorio KDE"),
    "notion": ("Notion", "notion-app", "Notas"),
    "obsidian": ("Obsidian", "obsidian", "Notas Markdown"),
    "ticktick": ("TickTick", "ticktick", "Tarefas"),
    "todoist": ("Todoist", "todoist", "Tarefas"),
    "evernote": ("Evernote", "evernote", "Notas"),
    "joplin": ("Joplin", "joplin", "Notas"),
    "zettlr": ("Zettlr", "zettlr", "Editor Markdown"),
    "marktext": ("MarkText", "marktext", "Editor Markdown"),
    "vscode": ("VS Code", "code", "Editor de codigo"),
    "vscodium": ("VSCodium", "vscodium", "Editor de codigo"),
    "sublime": ("Sublime Text", "sublime-text", "Editor de texto"),
    "gedit": ("gedit", "gedit", "Editor GNOME"),
    "kate": ("Kate", "kate", "Editor KDE"),
    "atom": ("Atom", "atom", "Editor GitHub"),
    "brackets": ("Brackets", "brackets", "Editor web"),
    "geany": ("Geany", "geany", "Editor leve"),
    "pluma": ("Pluma", "pluma", "Editor MATE"),
    "mousepad": ("Mousepad", "mousepad", "Editor XFCE"),
    "notepadqq": ("Notepadqq", "notepadqq", "Alternativa Notepad++"),
    "codeblocks": ("Code::Blocks", "codeblocks", "IDE C/C++"),
    "eclipse": ("Eclipse", "eclipse", "IDE Java"),
    "intellij": ("IntelliJ IDEA", "intellij-idea-community", "IDE Java/Kotlin"),
    "clion": ("CLion", "clion", "IDE C/C++"),
    "pycharm": ("PyCharm", "pycharm-community", "IDE Python"),
    "rider": ("Rider", "rider", "IDE .NET"),
    "goland": ("GoLand", "goland", "IDE Go"),
    "phpstorm": ("PHPStorm", "phpstorm", "IDE PHP"),
    "rubymine": ("RubyMine", "rubymine", "IDE Ruby"),
    "webstorm": ("WebStorm", "webstorm", "IDE JavaScript"),
    "datagrip": ("DataGrip", "datagrip", "IDE Database"),
    "gimp": ("GIMP", "gimp", "Editor de imagens"),
    "inkscape": ("Inkscape", "inkscape", "Editor vetorial"),
    "blender": ("Blender", "blender", "3D"),
    "krita": ("Krita", "krita", "Pintura digital"),
    "scribus": ("Scribus", "scribus", "Editoracao"),
    "darktable": ("Darktable", "darktable", "Fotografia RAW"),
    "rawtherapee": ("RawTherapee", "rawtherapee", "Fotografia RAW"),
    "digikam": ("DigiKam", "digikam", "Gerenciador fotos"),
    "gwenview": ("Gwenview", "gwenview", "Visualizador KDE"),
    "eog": ("Eye of GNOME", "eog", "Visualizador GNOME"),
    "nomacs": ("Nomacs", "nomacs", "Visualizador"),
    "shotwell": ("Shotwell", "shotwell", "Gerenciador fotos"),
    "kolourpaint": ("KolourPaint", "kolourpaint", "Pintura KDE"),
    "obs": ("OBS Studio", "obs-studio", "Gravacao/Streaming"),
    "kdenlive": ("Kdenlive", "kdenlive", "Editor de video"),
    "ffmpeg": ("FFmpeg", "ffmpeg", "Conversao de midia"),
    "handbrake": ("HandBrake", "handbrake", "Conversor video"),
    "avidemux": ("Avidemux", "avidemux", "Editor de video"),
    "pitivi": ("PiTiVi", "pitivi", "Editor de video GNOME"),
    "openshot": ("OpenShot", "openshot", "Editor de video"),
    "shotcut": ("Shotcut", "shotcut", "Editor de video"),
    "kazam": ("Kazam", "kazam", "Gravador de tela"),
    "peek": ("Peek", "peek", "GIF screencast"),
    "vokoscreen": ("VokoScreen", "vokoscreen", "Gravador de tela"),
    "simpleScreenRecorder": ("SimpleScreenRecorder", "simplescreenrecorder", "Gravador"),
    "miro": ("Miro", "miro", "Video"),
    "daVinci": ("DaVinci Resolve", "davinci-resolve", "Editor profissional"),
    "davinci": ("DaVinci Resolve", "davinci-resolve", "Editor profissional"),
    "audacity": ("Audacity", "audacity", "Editor de audio"),
    "filezilla": ("FileZilla", "filezilla", "FTP"),
    "cyberduck": ("Cyberduck", "cyberduck", "FTP/S3"),
    "nautilus": ("Nautilus", "nautilus", "Gerenciador GNOME"),
    "dolphin": ("Dolphin", "dolphin", "Gerenciador KDE"),
    "thunar": ("Thunar", "thunar", "Gerenciador XFCE"),
    "nemo": ("Nemo", "nemo", "Gerenciador Cinnamon"),
    "pcmanfm": ("PCManFM", "pcmanfm", "Gerenciador LXDE"),
    "qbittorrent": ("qBittorrent", "qbittorrent", "Torrent"),
    "deluge": ("Deluge", "deluge", "Torrent"),
    "transmission": ("Transmission", "transmission-gtk", "Torrent"),
    "ktorrent": ("KTorrent", "ktorrent", "Torrent KDE"),
    "amule": ("aMule", "amule", "eDonkey"),
    "git": ("Git", "git", "Controle de versao"),
    "docker": ("Docker", "docker", "Containerizacao"),
    "postman": ("Postman", "postman", "API Testing"),
    "insomnia": ("Insomnia", "insomnia", "API Testing"),
    "curl": ("cURL", "curl", "HTTP CLI"),
    "wget": ("Wget", "wget", "Download CLI"),
    "ssh": ("OpenSSH", "openssh", "SSH"),
    "putty": ("PuTTY", "putty", "SSH/Telnet"),
    "terminator": ("Terminator", "terminator", "Terminal"),
    "guake": ("Guake", "guake", "Terminal dropdown"),
    "tilix": ("Tilix", "tilix", "Terminal tiling"),
    "kitty": ("Kitty", "kitty", "Terminal GPU"),
    "alacritty": ("Alacritty", "alacritty", "Terminal GPU"),
    "tmux": ("Tmux", "tmux", "Terminal multiplexador"),
    "screen": ("Screen", "screen", "Terminal multiplexador"),
    "ansible": ("Ansible", "ansible", "Automacao"),
    "vagrant": ("Vagrant", "vagrant", "Dev environments"),
    "gradle": ("Gradle", "gradle", "Build tool"),
    "maven": ("Maven", "maven", "Build tool"),
    "cmake": ("CMake", "cmake", "Build system"),
    "make": ("Make", "make", "Build tool"),
    "gcc": ("GCC", "gcc", "Compilador"),
    "clang": ("Clang", "clang", "Compilador"),
    "rustc": ("Rust", "rustc", "Linguagem"),
    "go": ("Go", "go", "Linguagem"),
    "python": ("Python", "python3", "Linguagem"),
    "nodejs": ("Node.js", "nodejs", "Runtime JS"),
    "npm": ("NPM", "npm", "Gerenciador pacotes JS"),
    "yarn": ("Yarn", "yarn", "Gerenciador pacotes JS"),
    "mysql": ("MySQL", "mysql", "Banco de dados"),
    "mariadb": ("MariaDB", "mariadb", "Banco de dados"),
    "postgresql": ("PostgreSQL", "postgresql", "Banco de dados"),
    "sqlite": ("SQLite", "sqlite3", "Banco de dados"),
    "mongodb": ("MongoDB", "mongodb", "Banco NoSQL"),
    "redis": ("Redis", "redis", "Cache"),
    "apache": ("Apache", "apache2", "Servidor web"),
    "nginx": ("Nginx", "nginx", "Servidor web"),
    "lighttpd": ("Lighttpd", "lighttpd", "Servidor web"),
    "virtualbox": ("VirtualBox", "virtualbox", "Virtualizacao"),
    "qemu": ("QEMU", "qemu", "Virtualizacao"),
    "gnome-boxes": ("GNOME Boxes", "gnome-boxes", "Virtualizacao"),
    "virt-manager": ("Virt Manager", "virt-manager", "Virtualizacao"),
    "keepassxc": ("KeePassXC", "keepassxc", "Gerenciador senhas"),
    "bitwarden": ("Bitwarden", "bitwarden", "Senhas"),
    "veracrypt": ("VeraCrypt", "veracrypt", "Criptografia"),
    "gnupg": ("GPG", "gnupg", "Criptografia"),
    "openssl": ("OpenSSL", "openssl", "SSL/TLS"),
    "timeshift": ("Timeshift", "timeshift", "Backup sistema"),
    "backintime": ("Back In Time", "backintime", "Backup"),
    "grsync": ("Grsync", "grsync", "Rsync GUI"),
    "stacer": ("Stacer", "stacer", "Otimizador"),
    "bleachbit": ("BleachBit", "bleachbit", "Limpeza"),
    "gparted": ("GParted", "gparted", "Gerenciador de discos"),
    "gnome-disks": ("Disks", "gnome-disks", "Gerenciador de discos"),
    "baobab": ("Baobab", "baobab", "Uso de disco"),
    "filelight": ("Filelight", "filelight", "Uso de disco"),
    "htop": ("Htop", "htop", "Monitor de processos"),
    "btop": ("Btop", "btop", "Monitor de recursos"),
    "nvtop": ("NVTOP", "nvtop", "Monitor GPU NVIDIA"),
    "wireshark": ("Wireshark", "wireshark", "Sniffer de rede"),
    "nmap": ("Nmap", "nmap", "Scanner de rede"),
    "7zip": ("7-Zip", "p7zip-full", "Compactador"),
    "peazip": ("PeaZip", "peazip", "Compactador"),
    "ark": ("Ark", "ark", "Compactador KDE"),
    "file-roller": ("File Roller", "file-roller", "Compactador GNOME"),
    "xarchiver": ("Xarchiver", "xarchiver", "Compactador"),
    "engrampa": ("Engrampa", "engrampa", "Compactador MATE"),
    "evince": ("Evince", "evince", "Leitor PDF GNOME"),
    "okular": ("Okular", "okular", "Leitor PDF KDE"),
    "zathura": ("Zathura", "zathura", "Leitor PDF minimalista"),
    "foxit": ("Foxit", "foxitreader", "Leitor PDF"),
    "anydesk": ("AnyDesk", "anydesk", "Acesso remoto"),
    "teamviewer": ("TeamViewer", "teamviewer", "Acesso remoto"),
    "parsec": ("Parsec", "parsec", "Jogar remotamente"),
    "sunshine": ("Sunshine", "sunshine", "Game streaming"),
    "moonlight": ("Moonlight", "moonlight", "Game streaming"),
    "remmina": ("Remmina", "remmina", "Escritorio remoto"),
    "vinagre": ("Vinagre", "vinagre", "Escritorio remoto"),
    "krdc": ("KRDC", "krdc", "Escritorio remoto KDE"),
    "nomachine": ("NoMachine", "nomachine", "Acesso remoto"),
    "x2go": ("X2Go", "x2goclient", "Acesso remoto"),
    "sshfs": ("SSHFS", "sshfs", "Montar remote"),
    "dropbox": ("Dropbox", "dropbox", "Cloud storage"),
    "google-drive": ("Google Drive", "google-drive-ocamlfuse", "Cloud storage"),
    "mega": ("MEGA", "megasync", "Cloud storage"),
    "onedrive": ("OneDrive", "onedrive", "Cloud storage"),
    "rclone": ("Rclone", "rclone", "Cloud CLI"),
    "dosbox": ("DOSBox", "dosbox", "Emulador DOS"),
    "dosemu": ("DOSEMU", "dosemu", "Emulador DOS"),
    "scummvm": ("ScummVM", "scummvm", "Emulador jogos antigos"),
    "retroarch": ("RetroArch", "retroarch", "Emulador multi-sistema"),
    "pcsx2": ("PCSX2", "pcsx2", "Emulador PlayStation 2"),
    "ppsspp": ("PPSSPP", "ppsspp", "Emulador PSP"),
    "rpcs3": ("RPCS3", "rpcs3", "Emulador PS3"),
    "citra": ("Citra", "citra", "Emulador 3DS"),
    "yuzu": ("Yuzu", "yuzu", "Emulador Switch"),
    "ryujinx": ("Ryujinx", "ryujinx", "Emulador Switch"),
    "xenia": ("Xenia", "xenia", "Emulador Xbox"),
    "wine": ("Wine", "wine", "Executar Windows"),
    "winetricks": ("Winetricks", "winetricks", "Auxiliar Wine"),
    "playonlinux": ("PlayOnLinux", "playonlinux", "Jogos Windows"),
    "bottles": ("Bottles", "bottles", "Ambientes Windows"),
    "crossover": ("CrossOver", "crossover", "Windows compatibility"),
    "spectacle": ("Spectacle", "spectacle", "Screenshot KDE"),
    "gnome-screenshot": (" GNOME Screenshot", "gnome-screenshot", "Screenshot GNOME"),
    "flameshot": ("Flameshot", "flameshot", "Screenshot"),
    "shutter": ("Shutter", "shutter", "Screenshot"),
    "krunner": ("KRunner", "krunner", "Lancador KDE"),
    "ulauncher": ("ULauncher", "ulauncher", "Lancador"),
    "albert": ("Albert", "albert", "Lancador"),
    "synapse": ("Synapse", "synapse", "Lancador"),
    "kupfer": ("Kupfer", "kupfer", "Lancador"),
    "wofi": ("Wofi", "wofi", "Lancador Wayland"),
    "dmenu": ("dmenu", "dmenu", "Lancador"),
    "rofi": ("Rofi", "rofi", "Lancador/App launcher"),
    "kvantum": ("Kvantum", "kvantum", "Tema Qt"),
    "materia": ("Materia", "materia-gtk-theme", "Tema GTK"),
    "arc": ("Arc Theme", "arc-theme", "Tema GTK"),
    "oomox": ("Oomox", "oomox", "Criador de temas"),
    "lxappearance": ("LXAppearance", "lxappearance", "Aparencia LXDE"),
    "fonts": ("Font Manager", "font-manager", "Gerenciador de fontes"),
    "clipit": ("ClipIt", "clipit", "Clipboard"),
    "diodon": ("Diodon", "diodon", "Clipboard"),
    "klipper": ("Klipper", "klipper", "Clipboard KDE"),
}

GAME_NAMES = {
    "genshin impact": "Genshin Impact",
    "genshinimpact": "Genshin Impact",
    "yuanshen": "Genshin Impact",
    "honkai star rail": "Honkai: Star Rail",
    "honkai impact": "Honkai Impact 3rd",
    "star rail": "Honkai: Star Rail",
    "zenless": "Zenless Zone Zero",
    "zzz": "Zenless Zone Zero",
    "wuthering waves": "Wuthering Waves",
    "wuwa": "Wuthering Waves",
    "valorant": "Valorant",
    "league of legends": "League of Legends",
    "lol": "League of Legends",
    "fortnite": "Fortnite",
    "rocket league": "Rocket League",
    "minecraft": "Minecraft",
    "terraria": "Terraria",
    "cyberpunk": "Cyberpunk 2077",
    "witcher": "The Witcher 3",
    "gta": "Grand Theft Auto V",
    "red dead": "Red Dead Redemption 2",
    "rdr2": "Red Dead Redemption 2",
    "elden ring": "Elden Ring",
    "baldur": "Baldur's Gate 3",
    "bg3": "Baldur's Gate 3",
    "hogwarts": "Hogwarts Legacy",
    "starfield": "Starfield",
    "diablo": "Diablo IV",
    "overwatch": "Overwatch 2",
    "world of warcraft": "World of Warcraft",
    "wow": "World of Warcraft",
    "guild wars": "Guild Wars 2",
    "final fantasy": "Final Fantasy XIV",
    "ffxiv": "Final Fantasy XIV",
    "the elder scrolls": "The Elder Scrolls V: Skyrim",
    "skyrim": "The Elder Scrolls V: Skyrim",
    "fallout": "Fallout 4",
    "mass effect": "Mass Effect Legendary Edition",
    "dark souls": "Dark Souls III",
    "sekiro": "Sekiro: Shadows Die Twice",
    "resident evil": "Resident Evil 4",
    "street fighter": "Street Fighter 6",
    "tekken": "Tekken 8",
    "mortal kombat": "Mortal Kombat 1",
    "call of duty": "Call of Duty",
    "battlefield": "Battlefield",
    "assassin": "Assassin's Creed",
    "far cry": "Far Cry",
    "tom clancy": "Tom Clancy's",
    "rainbow six": "Rainbow Six Siege",
    "r6": "Rainbow Six Siege",
    "dota": "Dota 2",
    "counter strike": "Counter-Strike 2",
    "cs2": "Counter-Strike 2",
    "csgo": "Counter-Strike 2",
    "team fortress": "Team Fortress 2",
    "tf2": "Team Fortress 2",
    "apex": "Apex Legends",
    "destiny": "Destiny 2",
    "warframe": "Warframe",
    "path of exile": "Path of Exile",
    "poe": "Path of Exile",
    "lost ark": "Lost Ark",
    "new world": "New World",
    "palia": "Palia",
    "tower of fantasy": "Tower of Fantasy",
    "tof": "Tower of Fantasy",
    "blue protocol": "Blue Protocol",
    "throne and liberty": "Throne and Liberty",
    "tl": "Throne and Liberty",
    "pax dei": "Pax Dei",
    "ashes of creation": "Ashes of Creation",
    "nightingale": "Nightingale",
    "enshrouded": "Enshrouded",
    "palworld": "Palworld",
    "v rising": "V Rising",
    "valheim": "Valheim",
    "grounded": "Grounded",
    "sons of the forest": "Sons of the Forest",
    "forest": "Sons of the Forest",
    "satisfactory": "Satisfactory",
    "factorio": "Factorio",
    "rimworld": "RimWorld",
    "oxygen not included": "Oxygen Not Included",
    "oni": "Oxygen Not Included",
    "don't starve": "Don't Starve Together",
    "dst": "Don't Starve Together",
    "stardew valley": "Stardew Valley",
    "hades": "Hades",
    "hades ii": "Hades II",
    "celeste": "Celeste",
    "hollow knight": "Hollow Knight",
    "silksong": "Hollow Knight: Silksong",
    "dead cells": "Dead Cells",
    "risk of rain": "Risk of Rain 2",
    "ror2": "Risk of Rain 2",
    "returnal": "Returnal",
    "helldivers": "Helldivers 2",
    "hd2": "Helldivers 2",
    "deep rock": "Deep Rock Galactic",
    "drg": "Deep Rock Galactic",
    "left 4 dead": "Left 4 Dead 2",
    "l4d2": "Left 4 Dead 2",
    "payday": "Payday 2",
    "vermentide": "Warhammer: Vermintide 2",
    "darktide": "Warhammer 40k: Darktide",
    "space marine": "Warhammer 40k: Space Marine 2",
    "sm2": "Warhammer 40k: Space Marine 2",
    "armored core": "Armored Core VI",
    "ac6": "Armored Core VI",
    "lies of p": "Lies of P",
    "wo long": "Wo Long: Fallen Dynasty",
    "nioh": "Nioh 2",
    "star wars jedi": "Star Wars Jedi: Survivor",
    "jedi survivor": "Star Wars Jedi: Survivor",
    "dead space": "Dead Space",
    "alan wake": "Alan Wake 2",
    "control": "Control",
    "plague tale": "A Plague Tale: Requiem",
    "ghost of tsushima": "Ghost of Tsushima",
    "god of war": "God of War",
    "horizon": "Horizon Forbidden West",
    "spiderman": "Marvel's Spider-Man",
    "spider-man": "Marvel's Spider-Man",
    "spiderman 2": "Marvel's Spider-Man 2",
    "the last of us": "The Last of Us Part I",
    "tlou": "The Last of Us Part I",
    "uncharted": "Uncharted: Legacy of Thieves",
    "ratchet": "Ratchet & Clank: Rift Apart",
    "detroit": "Detroit: Become Human",
    "death stranding": "Death Stranding",
    "disco elysium": "Disco Elysium",
    "persona": "Persona 5 Royal",
    "p5r": "Persona 5 Royal",
    "metaphor": "Metaphor: ReFantazio",
    "like a dragon": "Like a Dragon",
    "yakuza": "Like a Dragon",
    "kingdom hearts": "Kingdom Hearts",
    "kh": "Kingdom Hearts",
    "nier": "NieR: Automata",
    "dragon quest": "Dragon Quest XI",
    "dqxi": "Dragon Quest XI",
    "octopath": "Octopath Traveler II",
    "triangle strategy": "Triangle Strategy",
    "fire emblem": "Fire Emblem",
    "xenoblade": "Xenoblade Chronicles",
    "zelda": "The Legend of Zelda",
    "metroid": "Metroid",
    "mario": "Super Mario",
    "sonic": "Sonic",
    "crash": "Crash Bandicoot",
    "spyro": "Spyro Reignited Trilogy",
    "psychonauts": "Psychonauts 2",
    "high on life": "High On Life",
    "hi fi rush": "Hi-Fi RUSH",
    "hifi rush": "Hi-Fi RUSH",
    "atomic heart": "Atomic Heart",
    "stray": "Stray",
    "vampire survivors": "Vampire Survivors",
    "halls of torment": "Halls of Torment",
    "broforce": "Broforce",
    "crab champions": "Crab Champions",
    "ultrakill": "ULTRAKILL",
    "doom": "DOOM Eternal",
    "doom 2016": "DOOM (2016)",
    "quake": "Quake",
    "quake champions": "Quake Champions",
    "wolfenstein": "Wolfenstein",
    "prey": "Prey",
    "dishonored": "Dishonored",
    "deathloop": "Deathloop",
    "ghostwire": "Ghostwire: Tokyo",
    "evil west": "Evil West",
    "shadow warrior": "Shadow Warrior 3",
    "trepang2": "Trepang2",
    "severed steel": "Severed Steel",
    "titanfall": "Titanfall 2",
    "tf2 single": "Titanfall 2",
    "battlebit": "BattleBit Remastered",
    "the finals": "THE FINALS",
    "xdefiant": "XDefiant",
    "marvel rivals": "Marvel Rivals",
    "concord": "Concord",
    "fragpunk": "FragPunk",
    "spectre divide": "Spectre Divide",
    "deadlock": "Deadlock",
    "mecha break": "Mecha BREAK",
    "delta force": "Delta Force",
    "delta force hawk oops": "Delta Force",
    "arma": "Arma 3",
    "squad": "Squad",
    "hell let loose": "Hell Let Loose",
    "post scriptum": "Post Scriptum",
    "insurgency": "Insurgency: Sandstorm",
    "ready or not": "Ready or Not",
    "ground branch": "Ground Branch",
    "six days": "Six Days in Fallujah",
    "bodycam": "Bodycam",
    "unrecord": "Unrecord",
    "stalker": "S.T.A.L.K.E.R. 2",
    "stalker 2": "S.T.A.L.K.E.R. 2",
    "metro": "Metro Exodus",
    "crysis": "Crysis Remastered",
    "dragon age": "Dragon Age: The Veilguard",
    "dav": "Dragon Age: The Veilguard",
    "avowed": "Avowed",
    "star wars outlaws": "Star Wars Outlaws",
    "indiana jones": "Indiana Jones and the Great Circle",
    "south park": "South Park",
    "borderlands": "Borderlands",
    "tiny tina": "Tiny Tina's Wonderlands",
    "wonderlands": "Tiny Tina's Wonderlands",
    "torchlight": "Torchlight",
    "grim dawn": "Grim Dawn",
    "last epoch": "Last Epoch",
    "wolcen": "Wolcen",
    "hokuto": "Hokuto",
    "fate": "Fate",
    "grand order": "Fate/Grand Order",
    "fgo": "Fate/Grand Order",
    "arknights": "Arknights",
    "blue archive": "Blue Archive",
    "girls frontline": "Girls' Frontline 2",
    "gfl2": "Girls' Frontline 2",
    "nikke": "Goddess of Victory: Nikke",
    "snowbreak": "Snowbreak: Containment Zone",
    "infinity nikki": "Infinity Nikki",
    "love and deepspace": "Love and Deepspace",
    "lads": "Love and Deepspace",
    "tower of saviors": "Tower of Saviors",
    "tos": "Tower of Saviors",
    "mu": "MU Online",
    "rappelz": "Rappelz",
    "metin2": "Metin2",
    "perfect world": "Perfect World",
    "pw": "Perfect World",
    "nostale": "NosTale",
    "shaiya": "Shaiya",
    "aion": "Aion",
    "lineage": "Lineage",
    "maplestory": "MapleStory",
    "ms": "MapleStory",
    "mabinogi": "Mabinogi",
    "dofus": "Dofus",
    "wakfu": "Wakfu",
    "tibia": "Tibia",
    "runescape": "RuneScape",
    "osrs": "Old School RuneScape",
    "old school": "Old School RuneScape",
    "albion": "Albion Online",
    "eve": "EVE Online",
    "second life": "Second Life",
    "vrchat": "VRChat",
    "rec room": "Rec Room",
    "neos": "Neos VR",
    "horizon worlds": "Horizon Worlds",
    "roblox": "Roblox",
    "pubg": "PUBG: Battlegrounds",
    "playerunknown": "PUBG: Battlegrounds",
    "warzone": "Call of Duty: Warzone",
    "wz": "Call of Duty: Warzone",
    "bloodhunt": "Bloodhunt",
    "naraka": "Naraka: Bladepoint",
    "eternal return": "Eternal Return",
    "supervive": "Supervive",
    "farlight": "Farlight 84",
    "hyper scape": "Hyper Scape",
}


def get_game_name(clean_name):
    for key, game in GAME_NAMES.items():
        if key in clean_name or clean_name in key:
            return game
    return None


def load_ports():
    if not os.path.exists(CACHE_FILE):
        return {}
    try:
        with open(CACHE_FILE) as f:
            data = json.load(f)
            if "_meta" in data:
                del data["_meta"]
            if "_template" in data:
                del data["_template"]
            return data
    except Exception:
        return {}


def check_native(clean_name):
    for keyword, (app, pkg, desc) in NATIVE.items():
        keyword_lower = keyword.lower()
        clean_lower = clean_name.lower()
        if keyword_lower in clean_lower or clean_lower in keyword_lower:
            return {"found": True, "app": app, "package": pkg, "desc": desc}
    return {"found": False}


def check_port(clean_name):
    ports = load_ports()
    for port_id, port in ports.items():
        keywords = port.get("keywords", [])
        for kw in keywords:
            kw_lower = kw.lower()
            clean_lower = clean_name.lower()
            if kw_lower in clean_lower or clean_lower in kw_lower:
                return {"found": True, "port": port, "id": port_id}
    return {"found": False}


def get_app_name(filename):
    name = os.path.basename(filename).lower()
    name = name.replace('.exe', '').replace('.msi', '')
    name = name.replace('setup', '').replace('installer', '').replace('install', '')
    name = name.replace('-', ' ').replace('_', ' ').strip()
    return name
