from __future__ import annotations
from pathlib import Path
from typing import Any


def export_modlist(
    entries: list[dict[str, Any]],
    output_path: str | Path,
) -> dict[str, Any]:
    """Export mod entries to MO2-compatible modlist.txt format.

    Each entry dict must have:
        name (str): mod display name
        enabled (bool): whether mod is active
        is_separator (bool, optional): whether it's a visual separator
        optional_files (list[dict], optional): [{name, enabled}, ...]
    """
    path = Path(output_path)
    lines: list[str] = [
        "# This file was automatically generated by Makai Forge Mod Manager.",
        "# Mod Organizer 2 compatible format.",
    ]

    for entry in entries:
        is_sep = entry.get("is_separator", False)
        enabled = entry.get("enabled", True)
        name = entry.get("name", "")

        if is_sep:
            prefix = "*" if enabled else "-"
            lines.append(f"{prefix}--- {name}")
        else:
            prefix = "*" if enabled else "-"
            lines.append(f"{prefix}{name}")

            for opt in entry.get("optional_files", []):
                opt_prefix = "+" if opt.get("enabled", True) else "-"
                lines.append(f"  {opt_prefix}{opt.get('name', '')}")

    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), "utf-8")

    return {
        "ok": True,
        "data": {
            "path": str(path.resolve()),
            "entries": len(entries),
            "lines": len(lines),
        },
    }
